#! /bin/bash
sudo apt-get update &&\
sudo apt install zsh &&\
sudo apt-get install powerline fonts-powerline &&\
git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh &&\
cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc &&\
chsh -s $(which zsh)

